# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://chiehting.com/"  # Include trailing slash
title = "Chiehting"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
#disqusShortname = "chiehting-com"

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[permalinks]
  posts  = "/:sections/:filename"

[taxonomies]
category = "category"
tag = "tags"
series = "series"

[module]
[[module.imports]]
    path = "github.com/hugomods/mermaid"


[params]
  [params.mermaid]
    js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'
